### ISSUE TITLE
.

### ISSUE THREAD

**Issue by GoldenAppleGuy** [ren7995/kai#5]

**Comment by ren7995** [comment]
Could you send the log?

**Comment by GoldenAppleGuy** [comment]
[E1C5034F-01AB-45E9-A9C1-D9C5759B21CD.txt](https://github.com/ren7995/kai/files/6526702/E1C5034F-01AB-45E9-A9C1-D9C5759B21CD.txt)
[31D036CF-F4DC-4117-851A-431AD9A1CA5F.txt](https://github.com/ren7995/kai/files/6526703/31D036CF-F4DC-4117-851A-431AD9A1CA5F.txt)

**Comment by GoldenAppleGuy** [comment]
This one may be more useful, from CrashReporter
[SpringBoard-2021-05-18-170807.symbolicated.txt](https://github.com/ren7995/kai/files/6526712/SpringBoard-2021-05-18-170807.symbolicated.txt)

**Comment by ren7995** [comment]
Got it. Kai needs lots of the code to be rewritten, but don't have the time run. Hopefully over the summer I'll be able to address this
